{
 "title": "Nacos",
 "tags": [ "nacos" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nacos_monitor{}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "nacos monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nacos_monitor{name=\"configCount\"})"
    }
   ]
  },
  {
   "title": "service count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='domCount'})"
    }
   ]
  },
  {
   "title": "ip count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='ipCount'})"
    }
   ]
  },
  {
   "title": "config count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='configCount', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling'})"
    }
   ]
  },
  {
   "title": "config push total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='getConfig', instance=~'$instance'}) by (name)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "content": "<html>\n<body>\n<center>\n<a href=\"https://nacos.io\">\n<img src=\"https://nacos.io/img/nacos.png\" style=\"height: 50px;\">\n</a>\n</center>\n</body>\n</html>"
  },
  {
   "title": "cpu",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(system_cpu_usage{instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", instance=~'$instance'})/sum(jvm_memory_max_bytes{area=\"heap\", instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "notify rt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nacos_timer_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(nacos_timer_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "rt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "qps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "avgPushCost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='avgPushCost', instance=~'$instance'})"
    }
   ]
  },
  { "title": "nacos detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "rt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~'/v1/cs/configs|/nacos/v1/ns', instance=~'$instance'}[1m])/rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri) * 1000"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "repeat": "group",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "load 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "leaderStatus",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='leaderStatus', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "configCount",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{name='configCount', instance=~'$instance'})"
    }
   ]
  }
 ]
}