server {
    listen              443 ssl;
    listen              [::]:443 ssl;
    http2               on;
    server_name         api.example.com;
    root                /var/www/api.example.com/public;

    # SSL
    ssl_certificate         /etc/nginx/ssl/api.example.com.crt;
    ssl_certificate_key     /etc/nginx/ssl/api.example.com.key;
    ssl_trusted_certificate /etc/nginx/ssl/ca.crt;

    # security
    include             nginxconfig.io/security.conf;

    # logging
    access_log          /var/log/nginx/access.log combined buffer=512k flush=1m;
    error_log           /var/log/nginx/error.log warn;

    # reverse proxy
    location /api/ {
        proxy_pass            http://apisix:9080;
        proxy_set_header Host $host;
        include               nginxconfig.io/proxy.conf;
    }

    # additional config
    include nginxconfig.io/general.conf;
}

# subdomains redirect
server {
    listen              443 ssl;
    listen              [::]:443 ssl;
    http2               on;
    server_name         *.api.example.com;

    # SSL
    ssl_certificate         /etc/nginx/ssl/api.example.com.crt;
    ssl_certificate_key     /etc/nginx/ssl/api.example.com.key;
    ssl_trusted_certificate /etc/nginx/ssl/ca.crt;

    return              301 https://api.example.com$request_uri;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name .api.example.com;
    return      301 https://api.example.com$request_uri;
}